# Generated by Django 5.0.4 on 2024-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_packages_subscriptiondetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subscription_details',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='car',
            new_name='cars',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='nam',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.DeleteModel(
            name='SubscriptionDetails',
        ),
    ]
