# Generated by Django 5.0.4 on 2024-04-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_vehicle_packages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='nam',
            new_name='name',
        ),
    ]
