# Generated by Django 5.0.4 on 2024-04-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_nam_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('Annual', 'Annual Subscription'), ('6/Month', '6-Month Subscription'), ('Monthly', 'Monthly Subscription')], default='', max_length=10)),
                ('type', models.CharField(choices=[('Premium', 'Premium'), ('Special', 'Special')], default='', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='cars',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='file',
            field=models.FileField(default='default_file.txt', upload_to='vehicle_files/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subscription'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
