# Generated by Django 5.0.4 on 2024-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subscription_remove_vehicle_cars_vehicle_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
