# Generated by Django 5.0.4 on 2024-04-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscription_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='file',
            field=models.FileField(upload_to='vehicle_files/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
