# Generated by Django 5.0.4 on 2024-04-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='package',
            name='car_subscription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.carsubscription'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
