# Generated by Django 5.0.4 on 2024-04-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_package_vehicle_package_car_subscription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
