# Generated by Django 5.0.4 on 2024-04-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
