# Generated by Django 5.0.4 on 2024-04-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle'),
        ),
    ]
