# Generated by Django 5.0.4 on 2024-04-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_package_car_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiondescription',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionData',
        ),
        migrations.DeleteModel(
            name='SubscriptionDescription',
        ),
    ]
