# Generated by Django 5.0.4 on 2024-04-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_subscriptiondescription_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscrationDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(default='', max_length=200)),
                ('vehicle_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
    ]
