# Generated by Django 5.0.4 on 2024-04-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('package_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.packages')),
                ('subscription_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.subscrationduration')),
                ('vehicle_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
    ]
