# Generated by Django 5.0.4 on 2024-05-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_descriptionprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
