# Generated by Django 5.0.4 on 2024-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_images/'),
        ),
    ]
