# Generated by Django 5.0.4 on 2024-05-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_category_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('comments', models.TextField(default='', max_length=500)),
                ('blog_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.blog')),
            ],
        ),
    ]
