# Generated by Django 5.0.4 on 2024-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_appoitmentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitmentschedule',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
